dist: xenial

jobs:
  include:
  - stage: deploy
    name: Docker
    language: ruby
    services:
      - docker
    script:
      - docker build -t slurk/audio-pilot .
    before_deploy:
      - echo "$REPOSITORY_PASS" | docker login -u "$REPOSITORY_USER" --password-stdin
    deploy:
      - provider: script
        script: docker push slurk/audio-pilot
        on:
          branch: master
  - stage: deploy
    name: Documentation
    language: python
    python: 3.7
    install: pip install sphinx sphinx_rtd_theme
    script: (cd docs && make html)
    after_success: touch docs/build/html/.nojekyll
    deploy:
      provider: pages
      skip-cleanup: true
      local_dir: docs/build/html
      github-token: $GH_TOKEN
      keep-history: true
      on:
        branch: master
