dist: xenial

jobs:
  include:
  - stage: deploy
    name: Documentation
    language: python
    python: 3.7
    install: pip install sphinx sphinx_rtd_theme
    script: (cd docs && make html)
    after_success: touch docs/build/html/.nojekyll
    deploy:
      provider: pages
      skip-cleanup: true
      local_dir: docs/build/html
      github-token: $GH_TOKEN
      keep-history: true
      on:
        branch: master
